name: quran_player
description: "Al-Quran Audio Player App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  audio_video_progress_bar: ^2.0.1
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.2.0
  device_preview: any
  dio: ^5.9.0
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.1.0
  get: ^4.7.3
  get_storage: ^2.1.1
  image_picker: ^1.2.0
  infinite_scroll_pagination: ^5.1.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  just_audio: ^0.9.42
  logger: ^2.5.0
  modal_bottom_sheet: ^3.0.0
  open_filex: ^4.7.0
  package_info_plus: ^9.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  json_serializable: ^6.9.0
  meta: ^1.17.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0

flutter_gen:
  output: lib/config/themes/generated
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
